// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsgyqhsajyiiluiutopg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzZ3lxaHNhanlpaWx1aXV0b3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDQ2MTEsImV4cCI6MjA3NDA4MDYxMX0.5UVUJKos77cXpjs317ZOA24crqjjBCiRhWoviqeAroM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});